# Generated by Django 2.2.7 on 2019-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(help_text='x', max_length=100)),
                ('Y', models.CharField(help_text='y', max_length=100)),
                ('uid', models.CharField(help_text='unique squirrel id', max_length=100)),
                ('hectare', models.CharField(help_text='hectare', max_length=100)),
                ('shift', models.CharField(help_text='shift', max_length=100)),
                ('date', models.DateField(help_text='date')),
                ('hectarenumber', models.CharField(help_text='hectare squirrel number', max_length=100)),
                ('age', models.CharField(help_text='age', max_length=100)),
                ('color', models.CharField(help_text='primary color', max_length=100)),
                ('hcolor', models.CharField(help_text='highlight fur color', max_length=100)),
                ('ccolor', models.CharField(help_text='combination color', max_length=100)),
                ('cnotes', models.CharField(help_text='color notes', max_length=100)),
                ('location', models.CharField(help_text='location', max_length=100)),
                ('measurement', models.CharField(help_text='measurement', max_length=100)),
                ('slocation', models.CharField(help_text='specific location', max_length=100)),
                ('running', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='running', max_length=10)),
                ('chasing', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='chasing', max_length=10)),
                ('climbing', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='climbing', max_length=10)),
                ('eating', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='eating', max_length=10)),
                ('foraging', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='foraging', max_length=10)),
                ('otheract', models.CharField(help_text='other activities', max_length=100)),
                ('kuks', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='kuks', max_length=10)),
                ('quaas', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='quaas', max_length=10)),
                ('moans', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='moans', max_length=10)),
                ('tflag', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='tail flags', max_length=10)),
                ('ttwitch', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='tail twitches', max_length=10)),
                ('approach', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='approach', max_length=10)),
                ('idiff', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='indifference', max_length=10)),
                ('runsfrom', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', help_text='runs from', max_length=10)),
                ('otherinter', models.CharField(help_text='other interactions', max_length=100)),
                ('ll', models.CharField(help_text='lat/long', max_length=100)),
                ('zc', models.CharField(help_text='zip codes', max_length=100)),
                ('cdistricts', models.CharField(help_text='community districts', max_length=100)),
                ('bb', models.CharField(help_text='borough boundaries', max_length=100)),
                ('ccd', models.CharField(help_text='city council districts', max_length=100)),
                ('pp', models.CharField(help_text='police precincts', max_length=100)),
            ],
        ),
    ]
